# -*- coding: utf-8 -*-
"""Potlapelli_SaiVarun_GENAI_Week1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZziwKOL-adWK53y8ZOmDHkIYBHvUIr7
"""

#Python Fundamentals for Generative AI
#TASK 1 - Python Basics & Operators

#1. Create a Python script that accepts two numbers from the user
a = int(input("Enter the First number:"))
b = int(input("Enter the second number:"))


#2. Perform all basic arithmetic operations (add, subtract, multiply, divide, modulus, power).
print (a + b)
print (a - b)
print (a * b)
print (a / b)
print (a % b)
print (a ** b)
print("All arrithmetic operations are performed")


#3. Demonstrate use of comparison and logical operators (>, <, ==, !=, and, or, not).
#comparison operators
print(a > b)
print(a < b)
print(a == b)
print(a != b)
#logical operators
print(a and b)
print(a or b)
print(not a)
print(not b)
print("All comparison and logical operators are performed")


#4. Print results clearly using formatted output (f-strings)

# Arithmetic operations using f-strings
print(f"Addition of {a} and {b} is {a + b}")
print(f"Subtraction of {a} and {b} is {a - b}")
print(f"Multiplication of {a} and {b} is {a * b}")
print(f"Division of {a} and {b} is {a / b}")
print("All the results are printed clearly using formatted output (f-strings)")

#Task 2: Lists and Arrays
#1. Create a list of 10 random integers.
import random
# Create a list of 10 random integers between 1 and 100
numbers = random.sample(range(1, 101), 10)
print(numbers)

#2. Perform the following operations:
# Add and remove elements.
# Find the maximum and minimum values.
# Sort the list.

#Creating the list
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print ("list")
#Adding the elements
list.append(11)
print("The list after adding the elements is:", list)

#Removing the elements
list.remove(5)
print("The list after removing the elements is:", list)

#Finding the maximum and minimum values
max_value = max(list)
min_value = min(list)
print("The maximum value in the list is:", max_value)
print("The minimum value in the list is:", min_value)

#Sorting the list
sorted_list = sorted(list)
print("The sorted list is:", sorted_list)

print("All the operations on the list are performed")

#3. Convert the list into a NumPy array and calculate:
# Mean, Median, and Standard Deviation.

import numpy as np

# list
numbers = [12, 45, 89, 23, 56, 34, 90, 18, 67, 100]

# Converting list to NumPy array
array = np.array(numbers)

print(f"NumPy Array: {array}")

# Calculate Mean, Median, and Standard Deviation
mean = np.mean(array)
median = np.median(array)
std_deviation = np.std(array)

# Display results using f-strings
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_deviation}")

print("List is coverted into Numpy array and mean,median and standard Deviation is calculated")

#Task 3: Dictionaries and Sets
#1. Create a dictionary named student with keys: name, course, marks.
student = {
    "name": "varun",
    "course": "GEN AI",
    "marks": [85]
}

print("Student Dictionary:")
print(student)

print("Student dictionary with keys is created ")

#2. Add a new key grade and assign a value based on marks (e.g., A/B/C).
#Adding grade based on marks
# Access the first mark in the list for comparison
if student["marks"][0] >= 80:
    student["grade"] = "A"
elif student["marks"][0] >= 60:
    student["grade"] = "B"
else:
    student["grade"] = "C"

# Display the dictionary
print(student)

print("New key grade is added to the dictionary")


#3. Print all keys and values using a loop
for i in student:
    print(i, student[i])

print("All keys and values are printed using a loop")

#4. Create two sets of AI tools

# Creating the first set of AI tools
ai_tools_set1 = {"TensorFlow", "PyTorch", "Keras", "Scikit-learn", "NLTK"}

# Creating the second set of AI tools
ai_tools_set2 = {"PyTorch", "Gensim", "SpaCy", "TensorFlow", "Hugging Face"}

print("AI Tools Set 1:", ai_tools_set1)
print("AI Tools Set 2:", ai_tools_set2)

#Task 4: File Handling
#1. Create a text file named ai_students.txt.
# Create a text file named ai_students.txt
file = open("ai_students.txt", "w")
file.close()

print("File ai_students.txt created successfully.")

#2. Write details of at least 5 students (name, marks, grade).
file = open("ai_students.txt", "w")
file.write("Name,Marks,Grade\n") # Changed separator to comma for easier splitting
file.write("Sai Varun,85,A\n")
file.write("Anjali,78,B\n")
file.write("Rahul,92,A\n")
file.write("Priya,65,B\n")
file.write("Kiran,54,C\n")
file.close() # Close the file after writing

print("Student details written to ai_students.txt successfully.")


#3. Read the file and display students who scored above 75 marks
print("\nStudents who scored above 75 marks:")
with open("ai_students.txt", "r") as file:
    lines = file.readlines()

    # Skip header line
    for line in lines[1:]:
        name, marks_str, grade = line.strip().split(',')
        marks = int(marks_str)
        if marks > 75:
            print(f"Name: {name}, Marks: {marks}, Grade: {grade}")

#Task 5: Real-World Mini Project
# ai_prompt_logger.py

from datetime import datetime

# 1. Accept user input (AI prompt)
prompt = input("Enter your AI prompt: ")

# 2 & 3. Save prompt with timestamp (append mode)
file = open("ai_prompts.txt", "a")
timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
file.write(f"[{timestamp}] {prompt}\n")

print("Prompt saved successfully.")